#! /bin/python3
import sys
from printing import print_results
from water_jug_problem import water_jug_solver


def main():
    """Main function."""
    print("Water jug problem")
    print("-----------------")
    jug_capacity_1 = int(input("Enter Jug 1 Capacity (X): "))
    jug_capacity_2 = int(input("Enter Jug 2 Capacity (Y): "))
    target = int(input("Enter desidered target amount (Z): "))
    print("------------------------------------")
    try:
        steps = water_jug_solver(
            jug_capacity_1=jug_capacity_1,
            jug_capacity_2=jug_capacity_2,
            target=target,
        )
        print_results(
            jug1_capacity=jug_capacity_1,
            jug2_capacity=jug_capacity_2,
            target=target,
            steps=steps,
        )
    except Exception as e:
        sys.stderr.write(f"{e}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
